name: 'Generate Github action test matrix'
description: 'Generate a (minimal) test matrix from continuous parameters'
branding:
  icon: 'cloud'
  color: 'blue'
inputs:
  parameters:
    description: 'Nested array with all possible parameters'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
