name: Test
on: pull_request

jobs:
  single-dimension:
    runs-on: ubuntu-latest
    name: Single dimension
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: matrix
        with:
          parameters: '{"a": [1, 2] }'
      - run: echo ${{ toJSON(steps.matrix.outputs.matrix) }}
      - run: if ${{ fromJSON(toJSON(steps.matrix.outputs.matrix)) != '[{"a":1},{"a":2}]' }}; then exit 1; fi
  two-dimensions:
    runs-on: ubuntu-latest
    name: Two dimensions
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: matrix
        with:
          parameters: '{"a": [1, 2], "b": ["hi", "ho"] }'
      - run: echo ${{ toJSON(steps.matrix.outputs.matrix) }}
      - run: if ${{ fromJSON(toJSON(steps.matrix.outputs.matrix)) != '[{"a":1,"b":"hi"},{"a":1,"b":"ho"},{"a":2,"b":"hi"}]' }}; then exit 1; fi

  summary:
    name: Test summary
    runs-on: ubuntu-latest
    needs:
      - single-dimension
      - two-dimensions
    if: always()
    steps:
      - run: if ${{ needs.single-dimension.result != 'success' }}; then exit 1; fi
      - run: if ${{ needs.two-dimensions.result != 'success' }}; then exit 1; fi
